name: smart_appointment
description: Smart Appointment Scheduling & Queue Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Database (cross-platform: mobile + web, pure Dart)
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.5

  # Unique IDs
  uuid: ^4.4.0

  # Date formatting
  intl: ^0.19.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # Shared Preferences
  shared_preferences: ^2.2.3

  # Google Fonts
  google_fonts: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
